### ISSUE TITLE
Harika.

### ISSUE THREAD

**Issue by Volkan0682** [ozkanozgur/arduino_model_lighting#1]
Muhteşem bir emek. Bir ölçekli plastik modelci olarak aradığım tamda buydu. Ancak daha fazla detay bulabileceğimiz bir siteniz yada vidyo içeriğini varsa muhteşem olur.

**Comment by ozkanozgur** [comment]
Çok teşekkür ederim. Kısmetse bir blog yazısı şeklinde ve youtube videosu şeklinde bir nasıl yapılır bölümü de yapmaya çalışacağım.
